### ISSUE TITLE
"Thumbnailing..." still occurs

### ISSUE THREAD

**Issue by Chiiruno** [bakape/meguca#879]
Doesn't work of course after ~10 seconds.
Seems to be related to cloudflare, since I got an image frame 502 for a different image right after which the event handler fixed.

**Comment by bakape** [comment]
Here's the thing: thumbnailing now does not go through Cloudflare.

**Comment by Chiiruno** [comment]
Might want to check c7601c84ce04e8e9e7d55696d431875cee3bcebf then.

**Comment by bakape** [comment]
Nope, we've had that before.

**Comment by bakape** [comment]
First I need to find it.

**Comment by Chiiruno** [comment]
Caused by captcha, need to upload the image first, or bring out the captcha without blocking.

**Comment by Chiiruno** [comment]
The captcha and the image upload process are somehow blocking each other.

**Comment by bakape** [comment]
Maybe it happens when a post is already allocated server-side without an image and then a captcha is requested for image insertion?  Need to test.

**Comment by Chiiruno** [comment]
That sounds about right.

**Comment by Chiiruno** [comment]
Is this fixed by d6ba4cd6caa606a53d3fa722d6ba5bfee027e7ac?

**Comment by bakape** [comment]
I don't know. Welcome to data races.

**Comment by Chiiruno** [comment]
I'm working on learning Rust for the touhou captcha and probably rewriting thumbnailer, so feel free to do the stuff I'm assigned to in the meantime if it comes up for some reason.
Of course, anything I can help with, I will.

**Comment by bakape** [comment]
I'll be busy bar small bursts for the next 1-2 weeks.

**Comment by bakape** [comment]
Nope, still happens. Interestingly cancelling image upload does not fix it, but doing it enough time to trigger a captcha and then completing it does. In other words this is likely unrelated to captchas themselves, but captcha completion resets some state that is causing this.

**Comment by bakape** [comment]
Considering a thumbnail is never generated, when stuck on "Thumbnailing...", the problem is likely server-side.

**Comment by Chiiruno** [comment]
Hm, maybe a data race in imager, or perhaps bad propagation between imager and main?

**Comment by bakape** [comment]
Probably imager
